### ISSUE TITLE
Why there are context embedding and word embedding, i think they share the same embedding matrix.

### ISSUE THREAD

**Issue by gouxute** [ozgurdemir/word2vec-keras#1]

**Comment by Ajk4** [comment]
@gouxute @ozgurdemir

+1
This implementation is incorrect. Context/input embedding should share weights. Similarly as in this gist https://gist.github.com/codekansas/15b3c2a2e9bc7a3c345138a32e029969

**Comment by bledson** [comment]
From a footer note in "word2vec Explained: Deriving Mikolov et al.’s Negative-Sampling Word-Embedding Method" (Yoav Goldberg and Omar Levy): 

> Throughout this note, we assume that the words and the contexts come from distinct vocabularies, so that, for example, the vector associated with the word dog will be different from the vector associated with the context dog. This assumption follows the literature, where it is not motivated. One motivation for making this assumption is the following: consider the case where both the word dog and the context dog share the same vector v. Words hardly appear in the contexts of themselves, and so the model should assign a low probability to p(dog|dog), which entails assigning a low value to v · v which is impossible.

**Comment by ozgurdemir** [comment]
Sorry for the late reply. Have been ooo. I think @Bledson cited a good paragraph from which it's clear that different vectors are used for words and embeddings. You may also have a look at the original work2vec C implementation where also different vectors are used for words and contexts. The original implementation is only using the word embeddings to detect similarities. Pennington et. al mentioned in their "GloVe: Global Vectors for Word Representation" paper that averaging the context and word embeddings might give slightly better results than using the word embeddings alone. Might be worth a try depending on your problem.
